version: '3'
services:
  backend:
    image: handyman-backend
    build: ./backend
    ports:
      - "8181:8181"
    volumes:
      - ./src:/usr/src/re_assignment
      - /usr/src/re_assignment/node_modules
